export { default as Head } from './head';
export { default as Layout } from './layout';
export { default as Loader } from './loader';
export { default as Menu } from './menu';
export { default as Nav } from './nav';
export { default as Side } from './side';
export { default as Email } from './email';
export { default as Social } from './social';
export { default as Footer } from './footer';
